# Generated by Django 3.0.3 on 2020-03-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0003_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ssh_port',
        ),
    ]
