# Generated by Django 3.0.3 on 2020-04-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0004_remove_device_ssh_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='scripts',
            field=models.FileField(default='NO SCRIPTS', upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
