# Generated by Django 3.2 on 2021-04-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0006_auto_20200406_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='netauto.device')),
                ('device_interface', models.CharField(max_length=200)),
                ('window_size', models.IntegerField()),
                ('sampling_interval', models.IntegerField()),
                ('elastic_host', models.GenericIPAddressField()),
                ('elastic_index', models.CharField(max_length=255)),
                ('filebeat_host', models.GenericIPAddressField()),
                ('filebeat_port', models.BigIntegerField()),
            ],
        ),
    ]
